on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Render and Deploy to Netlify



jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render English
        run: quarto render ${{ inputs.path }} --profile english
        
      - name: Render French
        run: quarto render ${{ inputs.path }} --profile french

      # UNCOMMENT THESE LINES TO DO A DEPLOYMENT TO NETLIFY
      # Require secrets added first  
      #- name: Publish
      #  uses: netlify/actions/cli@master
      #  with:
      #    args: deploy --dir=_site
      #  env:
      #    NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #    NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          
